#!/usr/bin/env node

require('ts-node/register');

// TODO add start up text here

console.log("     __          _       ___ _             ");
console.log("  /\\ \\ \\___  ___| |_    / __\\ | ___   __ _ ");
console.log(" /  \\/ / _ \\/ __| __|  /__\\/\/ |/ _ \\ \/ _` |");
console.log("/ /\\  /  __/\\__ \\ |_  / \\/  \\ | (_) | (_| |");
console.log("\\_\\ \\/ \\___||___/\\__| \\_____\/_|\\___/ \\__, |");
console.log("                                     |___\/ ");

var bootstrap = require('./src/cli');