version: "3"

services:
    db:
        image: mongo:latest
        environment:
          - MONGODB_USER="root"
          - MONGODB_PASS="root"
        volumes:
          - ./.docker/mongo-data:/data/db
        ports:
          - 27017:27017

    node:
        build:
            context: '.docker/node'
        working_dir: /var/www
        volumes:
          - ./:/var/www
        links:
          - db
        ports:
          - 3000:3000

    mongoAdmin:
        image: mrvautin/adminmongo
        ports:
          - 1234:1234